alter table SGA_STUDENT_SUBJECT_COURSE add constraint FK_SGA_STUDENT_SUBJECT_COURSE_ON_STUDENT foreign key (STUDENT_ID) references SGA_STUDENT(ID);
alter table SGA_STUDENT_SUBJECT_COURSE add constraint FK_SGA_STUDENT_SUBJECT_COURSE_ON_SUBJECT foreign key (SUBJECT_ID) references SGA_SUBJECT(ID);
create index IDX_SGA_STUDENT_SUBJECT_COURSE_ON_STUDENT on SGA_STUDENT_SUBJECT_COURSE (STUDENT_ID);
create index IDX_SGA_STUDENT_SUBJECT_COURSE_ON_SUBJECT on SGA_STUDENT_SUBJECT_COURSE (SUBJECT_ID);
